#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli
# For more information: https://github.com/devcontainers-contrib/cli

set -e

source dev-container-features-test-lib

check "asdf-plugin-manager version" asdf-plugin-manager version
check "asdf plugin list" asdf plugin list

reportResults
