name: 'List file names'
description: 'Get a json list of the files listed in the specified folder'
inputs:
  path:
    description: 'Folder to list'
    required: true
outputs:
  all_features: # id of output
    description: 'A JSON formatted list of generated and manually crafted features'
    value: ${{ steps.set-filenames.outputs.all_features }}
  generated_features: # id of output
    description: 'A JSON formatted list of generated features'
    value: ${{ steps.set-filenames.outputs.generated_features }}

runs:
  using: 'composite'
  steps:
    - run: sudo apt update && sudo apt install tree jq -y
      shell: bash
    - id: set-filenames
      shell: bash
      run: |
        cd ${{ inputs.path }}
        
        sudo tree -J  ./feature_specs | sudo jq -c '.[0].contents | map(.name) | map(sub(".yaml"; ""))' > specs.json
        sudo tree -J -d  ./src | sudo jq -c '.[0].contents | map(.name)' > folders.json

        all_features=$(jq -sc '.[0] + .[1] | unique'  folders.json specs.json)
        generated_features=$(cat specs.json)

        echo "generated_features=$generated_features" >> $GITHUB_OUTPUT
        echo "all_features=$all_features" >> $GITHUB_OUTPUT