#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

curl https://raw.githubusercontent.com/go-task/task/main/completion/bash/task.bash > /etc/bash_completion.d/task.bash
